package org.freejava.windowstools;

import java.io.File;

import junit.framework.TestCase;

/**
 * The class <code>CygwinSupportTest</code> contains tests for the class {@link
 * <code>CygwinSupport</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 8/30/11 1:31 PM
 *
 * @author Thai Ha
 *
 * @version $Revision$
 */
public class CygwinSupportTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public CygwinSupportTest(String name) {
		super(name);
	}
	public void testShell() throws Exception {
		CygwinSupport support = new CygwinSupport();
		support.shell("cygwin", new File("C:\\"), "C:\\cygwin");
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames =
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods =
 * package = org.freejava.tools
 * package.sourceFolder = org.freejava.javasourceattachertests/src
 * superclassType = junit.framework.TestCase
 * testCase = CygwinSupportTest
 * testClassType = org.freejava.tools.handlers.start.CygwinSupport
 */