package org.freejava.windowstools;

import java.io.File;

import junit.framework.TestCase;

/**
 * The class <code>MingwSupportTest</code> contains tests for the class {@link
 * <code>MingwSupport</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 8/30/11 11:13 AM
 *
 * @author Thai Ha
 *
 * @version $Revision$
 */
public class MingwSupportTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public MingwSupportTest(String name) {
		super(name);
	}

	public void testShell() throws Exception {
		MingwSupport support = new MingwSupport();
		support.shell("bash", new File("C:\\"), "C:\\MinGW");
	}
	public void testMsgbox() throws Exception {
		WindowsAPI.MessageBox(null, "Hello world", "Hello", WindowsAPI.MB_OKCANCEL);

	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames =
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods =
 * package = org.freejava.tools
 * package.sourceFolder = org.freejava.javasourceattachertests/src
 * superclassType = junit.framework.TestCase
 * testCase = MingwSupportTest
 * testClassType = org.freejava.tools.handlers.start.MingwSupport
 */