package org.freejava.windowstools;

import junit.framework.TestCase;

/**
 * The class <code>MingwInstallerTest</code> contains tests for the class
 * {@link <code>MingwInstaller</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 9/1/11 2:43 PM
 *
 * @author Thai Ha
 *
 * @version $Revision$
 */
public class MingwInstallerTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public MingwInstallerTest(String name) {
		super(name);
	}

	/**
	 * Run the void install(java.lang.Object) method test
	 */
	public void testInstall() {
		MingwInstaller fixture = new MingwInstaller();
		fixture.install("D:\\MinGW");
	}

	public void testCreateExplorerCommand() {
		MingwInstaller fixture = new MingwInstaller();
		fixture.createExplorerCommand("MSYS Here", "c:\\WINDOWS\\system32\\cmd.exe");

	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames =
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = install(Qjava.lang.Object;)
 * package = org.freejava.windowstools
 * package.sourceFolder = org.freejava.windowstoolstests/src
 * superclassType = junit.framework.TestCase
 * testCase = MingwInstallerTest
 * testClassType = org.freejava.windowstools.MingwInstaller
 */